name: Increment version

on:
  workflow_dispatch:
    inputs:
      increment-version:
        description: Semantic versioning
        required: true
        default: patch
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  increment-version:
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    steps:
      - id: generate_token
        uses: tibdex/github-app-token@v1.7.0
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: actions/checkout@v3
        with:
          token: ${{ steps.generate_token.outputs.token }}
      - name: Version up
        id: version
        run: |
          set -x
          version=$(npm --no-git-tag-version version $INCREMENT_VERSION)
          echo "version=${version}" >> $GITHUB_OUTPUT
          sed -i -e "s|${GITHUB_REPOSITORY}@v[.0-9]\+|${GITHUB_REPOSITORY}@${version}|g" README.md .github/workflows/released.yml
          git diff
        env:
          INCREMENT_VERSION: ${{ github.event.inputs.increment-version }}
      - uses: snow-actions/git-config-user@v1.0.0
      - name: Commit & PR
        run: |
          set -x
          branch="release/${VERSION}"
          git switch -c ${branch}
          git add .
          git commit -m "${VERSION}"
          git push origin ${branch}
          gh pr create --base ${GITHUB_REF_NAME} --head ${branch} --assignee ${GITHUB_ACTOR} --title ${VERSION} --body ''
        env:
          VERSION: ${{ steps.version.outputs.version }}
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
